const users = require('./main/user')
const stores = require('./main/store')
const app_user = require('./main/app_user')
const store_users = require('./main/store_user')
const products = require('./main/product')
const categories = require('./main/category')
const order_details = require('./main/order_details')
const orders = require('./main/orders')
const cmsusers = require('./cms/cmsusers_router')
const inventory = require('./main/inventory')
const req_inventory = require('./main/req_inventory')
const company = require('./main/company')
const file = require('./main/file')
const multiple = require('./main/multiple')
const service = require('./main/service')
const service_provider = require('./main/service_provider')
const service_review = require('./main/service_review')
const service_provider_review = require('./main/service_provider_review')
const service_provider_details = require('./main/service_provider_details')
const booking_details = require('./main/booking_details')
const bookings = require('./main/bookings')
const service_provider_balance = require('./main/service_provider_balance')
const app_user_address = require('./main/app_user_address')
const reception = require('./main/reception')


module.exports = (router) => {
    router.get('/', function(req, res) {
        res.send('WELCOME TO API');
    });
    order_details(router)
    orders(router)
    users(router)
    stores(router)
    store_users(router)
    file(router)
    inventory(router)
    req_inventory(router)
    categories(router)
    cmsusers(router)
    products(router)
    company(router)
    multiple(router)
    app_user(router)
    service(router)
    service_provider(router)
    service_provider_review(router)
    service_review(router)
    service_provider_details(router)
    booking_details(router)
    bookings(router)
    service_provider_balance(router)
    app_user_address(router)
    reception(router)
}
